[package]
name = "wayvoice"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
config = { version = "0.15", features = ["toml"] }
dirs = "6"
reqwest = { version = "0.12", features = ["multipart", "rustls-tls", "json"], default-features = false }
tokio = { version = "1", features = ["rt", "process", "io-util", "fs", "sync", "net", "signal", "macros", "time"] }
log = "0.4"
env_logger = "0.11"
gtk4 = { version = "0.9" }
gtk4-layer-shell = { version = "0.5" }
notify = "8.2.0"
toml_edit = "0.25.4"

[profile.release]
opt-level = "z"
lto = true
strip = true
